import Head from 'next/head'
import { BiUserPlus } from 'react-icons/bi'
import Table from '@/components/table'
import Form from '@/components/form'
import { useState } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import { toggleChangeAction, deleteAction } from '@/redux/reducer'
import { deleteUser, getUser } from '@/lib/helper'
import { useQueryClient } from 'react-query'

export default function Home() {

  const visible = useSelector((state)=>state.app.client.toggleForm)
  const deleteId = useSelector(state => state.app.client.deleteId)
  const queryclient = useQueryClient();

  const dispatch = useDispatch()

  const handler = () => {
    dispatch(toggleChangeAction())
  }

  const deletehandler = async() => {
    if(deleteId){
      await deleteUser(deleteId);
      await queryclient.prefetchQuery('users', getUser)
      await dispatch(deleteAction(null))
    }
  }

  const concelhandler = async () => {
    console.log("Cancel")
    await dispatch(deleteAction(null))
  }

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='py-5'>
        <h3 className='text-xl md:text-5xl text-center font-bold py-10'>
          CRUD Application
        </h3>
        <div className='container mx-auto flex justify-between py-5 border-b'>
            <div className='left flex gap-3'>
              <button onClick={handler} className='flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-100 hover:border-indigo-500 hover:text-gray-800'>
                Add Employee <span className='px-1'> <BiUserPlus size={23}></BiUserPlus> </span>
              </button>
          </div>
          {deleteId ? DeleteComponent({deletehandler, concelhandler}):<></>}
        </div>
        {/* Collapsable form */}
          { visible ? <Form></Form> : <></>}
        {/* Table  */} 
        <div className='container mx-auto'>
          <Table></Table>
        </div>
      </main>
    </section>
  )
}


function DeleteComponent({ deletehandler, concelhandler}){
  return(
    <div className='flex gap-5'>
      <button> Are you sure?</button>
      <button onClick={deletehandler} className='flex bg-red-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:border-red-500 hover:text-gray-50'>
        Yes</button>
      <button onClick={concelhandler} className='flex bg-green-500 text-white px-4 py-2 border rounded-md hover:bg-green-500 hover:border-green-500 hover:text-gray-50'>
        No</button>
    </div>
  )
}